### ISSUE TITLE
credentials

### ISSUE THREAD

**Issue by wattwood** [ipython/ipython-ansible-jenkins#3]
How are you getting credentials to work with Jenkins?  I have it as far as copying keys, setting them in the credentials.xml file, however, when I go into Jenkins, it re-generates a key and re-encrypts the passwords, which breaks all creds.

**Comment by takluyver** [comment]
@rgbkrk , can you answer this? I don't really understand the ansible set up.

**Comment by rgbkrk** [comment]
Looks like we're not setting up any creds and building a fresh Jenkins box each time.

**Comment by takluyver** [comment]
Closing because we're dropping our Jenkins server, and thus this repo.
