### ISSUE TITLE
Is this still an active repo?

### ISSUE THREAD

**Issue by JamiesHQ** [ipython/ipython-ansible-jenkins#4]
Hi @minrk, @takluyver, @rgbkrk - we're doing some spring cleaning across the Jupyter & IPython Orgs and moving some of the older and/or deprecated content over to a newly minted ["Jupyter Attic"]  (https://github.com/jupyter-attic). You may see several related issues from me over the next week or so. 

*Is [ipython/ipython-ansible-jenkins](https://github.com/ipython/ipython-ansible-jenkins) still an active repo? Is it needed, is it being used, can it be deprecated?*

If it can be deprecated, I will make a note in the README.md file and pre-pend "DEPRECATED" to the title. I can then either move the repo directly to the Jupyter Attic or schedule a date a few months out for moving the repo to the Attic. This date will be included in the deprecation message in the README.md file. 

Thanks!

**Comment by Carreau** [comment]
I believe that's what's power https://jenkins.jupyter.org/ (yes it's a thing) .

**Comment by minrk** [comment]
Yup, it's still in use.

**Comment by JamiesHQ** [comment]
@fperez @ellisonbg : FYI

**Comment by fperez** [comment]
great, no problem. Then this goes into the 'services' category. Thanks!
